# parameters configuration
mode: predict_gui
root: /root/
predefined_dataset: CIFAR10
classes:
  [
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck",
  ]
max_samples: null
batch_size: 32
num_workers: 1
device: cuda
lr: 1e-3
model_name: tf_mobilenetv3_small_minimal_100
in_chans: 3
loss_function_name: BCEWithLogitsLoss
data_balance: False
checkpoint_path: pretrained/CIFAR10_test_accuracy_0.6230031948881789/checkpoints/epoch=31-step=39999-val_loss=0.2440.ckpt
seed: 0
early_stopping: True
patience: 3
default_root_dir: save/
gpus: 1
precision: 32
max_epochs: 100
color_space: RGB # (3x8-bit pixels, true color)
web_interface: True
examples:
  [
    "examples/CIFAR10/appaloosa_s_001946.png",
    "examples/CIFAR10/auto_s_000561.png",
    "examples/CIFAR10/bufo_marinus_s_001549.png",
    "examples/CIFAR10/gondola_s_000055.png",
    "examples/CIFAR10/wrecker_s_001908.png",
  ]
tuning_test: False
cpu_resources_per_trial: 1
gpu_resources_per_trial: 0.25
num_samples: -1

# transforms configuration
transforms_config:
  train:
    Resize:
      - 32
      - 32
    ColorJitter:
    RandomRotation: 90
    ToTensor:
    RandomErasing:

  val:
    Resize:
      - 32
      - 32
    ToTensor:

  test:
    Resize:
      - 32
      - 32
    ToTensor:

  predict:
    Resize:
      - 32
      - 32
    ToTensor:

# target transforms configuration
target_transforms_config:
  train:
    LabelSmoothing:
      alpha: 0.2
      num_classes: null

  val:
    OneHotEncoder:
      num_classes: null

  test:
    OneHotEncoder:
      num_classes: null

  predict:
    OneHotEncoder:
      num_classes: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10

# hyperparameter space configuration
hyperparameter_space_config:
  lr:
    uniform:
      lower: 1e-4
      upper: 1e-1

  max_epochs:
    randint:
      lower: 100
      upper: 500
