# parameters configuration
mode: train
root: data/
predefined_dataset: MNIST
classes:
  [
    "0 - zero",
    "1 - one",
    "2 - two",
    "3 - three",
    "4 - four",
    "5 - five",
    "6 - six",
    "7 - seven",
    "8 - eight",
    "9 - nine",
  ]
max_samples: null
batch_size: 32
num_workers: 0
device: cuda

# transforms configuration
transforms_config:
  train:
    Resize:
      - 224
      - 224
    ColorJitter:
    RandomRotation: 90
    ToTensor:
    RandomErasing:

  val:
    Resize:
      - 224
      - 224
    ToTensor:

  test:
    Resize:
      - 224
      - 224
    ToTensor:

  predict:
    Resize:
      - 224
      - 224
    ToTensor:

# target transforms configuration
target_transforms_config:
  train:
    LabelSmoothing:
      alpha: 0.2
      num_classes: null

  val:
    OneHotEncoder:
      num_classes: null

  test:
    OneHotEncoder:
      num_classes: null

  predict:
    OneHotEncoder:
      num_classes: null
