# parameters configuration
mode: train
root: data/
predefined_dataset: CIFAR10
classes:
  [
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck",
  ]
max_samples: null
batch_size: 32
num_workers: 0
device: cuda
lr: 1e-3
model_name: tf_mobilenetv3_small_minimal_100
in_chans: 3
loss_function_name: BCEWithLogitsLoss
data_balance: False
checkpoint_path: null
seed: 0
early_stopping: True
patience: 3
default_root_dir: save/
gpus: 1
precision: 32
max_epochs: 100
color_space: RGB # (3x8-bit pixels, true color)
tuning_test: False
cpu_resources_per_trial: 1
gpu_resources_per_trial: 1
num_samples: 100

# transforms configuration
transforms_config:
  train:
    Resize:
      - 32
      - 32
    ColorJitter:
    RandomRotation: 90
    ToTensor:
    RandomErasing:

  val:
    Resize:
      - 32
      - 32
    ToTensor:

  test:
    Resize:
      - 32
      - 32
    ToTensor:

  predict:
    Resize:
      - 32
      - 32
    ToTensor:

# target transforms configuration
target_transforms_config:
  train:
    LabelSmoothing:
      alpha: 0.2
      num_classes: null

  val:
    OneHotEncoder:
      num_classes: null

  test:
    OneHotEncoder:
      num_classes: null

  predict:
    OneHotEncoder:
      num_classes: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10

# hyperparameter space configuration
hyperparameter_space_config:
  lr:
    uniform:
      lower: 1e-4
      upper: 1e-1

  max_epochs:
    randint:
      lower: 10
      upper: 200
