# parameters configuration
mode: predict_gui
root: /root/
predefined_dataset: MNIST
classes:
  [
    "0 - zero",
    "1 - one",
    "2 - two",
    "3 - three",
    "4 - four",
    "5 - five",
    "6 - six",
    "7 - seven",
    "8 - eight",
    "9 - nine",
  ]
max_samples: null
batch_size: 32
num_workers: 1
device: cuda
lr: 1e-3
model_name: tf_mobilenetv3_small_minimal_100
in_chans: 1
loss_function_name: BCEWithLogitsLoss
data_balance: False
checkpoint_path: pretrained/MNIST_test_accuracy_0.976138178913738/checkpoints/epoch=11-step=17999-val_loss=0.1611.ckpt
seed: 0
early_stopping: True
patience: 3
default_root_dir: save/
gpus: 1
precision: 32
max_epochs: 100
color_space: L # (8-bit pixels, black and white)
web_interface: True
examples:
  [
    "examples/MNIST/00000_7.png",
    "examples/MNIST/00001_2.png",
    "examples/MNIST/00002_1.png",
    "examples/MNIST/00003_0.png",
    "examples/MNIST/00004_4.png",
    "examples/MNIST/00007_9.png",
    "examples/MNIST/00011_6.png",
    "examples/MNIST/00061_8.png",
    "examples/MNIST/00433_5.png",
    "examples/MNIST/00449_3.png",
  ]
tuning_test: False
cpu_resources_per_trial: 1
gpu_resources_per_trial: 0.25
num_samples: -1

# transforms configuration
transforms_config:
  train:
    Resize:
      - 28
      - 28
    ColorJitter:
    RandomRotation: 90
    ToTensor:
    RandomErasing:

  val:
    Resize:
      - 28
      - 28
    ToTensor:

  test:
    Resize:
      - 28
      - 28
    ToTensor:

  predict:
    Resize:
      - 28
      - 28
    ToTensor:

# target transforms configuration
target_transforms_config:
  train:
    LabelSmoothing:
      alpha: 0.2
      num_classes: null

  val:
    OneHotEncoder:
      num_classes: null

  test:
    OneHotEncoder:
      num_classes: null

  predict:
    OneHotEncoder:
      num_classes: null

# optimizers configuration
optimizers_config:
  Adam:
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
    weight_decay: 0
    amsgrad: False

# learning rate schedulers configuration
lr_schedulers_config:
  CosineAnnealingLR:
    T_max: 10

# hyperparameter space configuration
hyperparameter_space_config:
  lr:
    uniform:
      lower: 1e-4
      upper: 1e-1

  max_epochs:
    randint:
      lower: 100
      upper: 500
